Repository coopiteasy/vertical-cooperative, pull requests merged in 2022-09, with the labels that each got.

#367 [REM] create button from subscription register
  cooperator/views/subscription_register_view.xml
Labels: needs review, bot is merging ⏳

#360 [FIX] l10n_be_cooperator: Typo
  l10n_be_cooperator/data/mail_template_data.xml
  l10n_be_cooperator/i18n/fr_BE.po
  l10n_be_cooperator/i18n/l10n_be_cooperator.pot
Labels: needs review, bot is merging ⏳

#349 [REM] email_template_config dep from cooperator
  cooperator/__manifest__.py
Labels: needs review, bot is merging ⏳

#343 [FIX] l10n_be_cooperator: tax shelter email_template
  l10n_be_cooperator/data/mail_template_data.xml
Labels: needs review, bot is merging ⏳

#365 [IMP] remove mention of bees in placeholders
  cooperator_website/views/subscription_template.xml
Labels: needs review, bot is merging ⏳

#346 Create USAGE.rst
  cooperator/readme/ROADMAP.rst
  cooperator/readme/USAGE.rst
  cooperator/readme/newsfragments/346.doc.rst
  l10n_be_cooperator/__manifest__.py
  l10n_ch_cooperator/__manifest__.py
  l10n_es_cooperator/__manifest__.py
  l10n_fr_cooperator/__manifest__.py
Labels: needs review, bot is merging ⏳

#364 [REM] update_partner_info wizard
  cooperator/__manifest__.py
  cooperator/views/res_partner_view.xml
  cooperator/wizard/__init__.py
  cooperator/wizard/update_partner_info.py
  cooperator/wizard/update_partner_info.xml
Labels: needs review, bot is merging ⏳

#383 [REM] cooperator: jquery.inputmask.bundle.js
  .eslintignore
  .pre-commit-config.yaml
  cooperator_website/static/src/js/cooperator.js
  cooperator_website/static/src/js/jquery.inputmask.bundle.js
  cooperator_website/views/subscription_template.xml
  easy_my_coop_loan_website/static/src/js/loan_issue.js
Labels: needs review, bot is merging ⏳, approved

#370 [14.0][FIX] fix multiple subscription request glitches
  cooperator/data/mail_template_data.xml
  cooperator/i18n/cooperator.pot
  cooperator/i18n/fr.po
  cooperator/i18n/fr_BE.po
  cooperator/migrations/14.0.1.1.0/post-remove_subscription_request_subscription_type.py
  cooperator/models/partner.py
  cooperator/models/subscription_request.py
  cooperator/tests/test_cooperator.py
Labels: needs review, bot is merging ⏳

#388 [14.0][REM] cooperator_website: jquery.inputmask.bundle.js
  .eslintignore
  cooperator_website/static/src/js/cooperator.js
  cooperator_website/static/src/js/jquery.inputmask.bundle.js
  cooperator_website/views/subscription_template.xml
Labels: needs review, bot is merging ⏳

#372 [12.0][IMP] cooperator: backport changes from migration to 14.0
  cooperator/__manifest__.py
  cooperator/data/data.xml
  cooperator/data/mail_template_data.xml
  cooperator/i18n/cooperator.pot
  cooperator/i18n/easy_my_coop.pot
  cooperator/i18n/fr.po
  cooperator/i18n/fr_BE.po
  cooperator/migrations/12.0.6.0.0/post-fix_subscription_request_names.py
  cooperator/migrations/12.0.6.0.0/post-remove_subscription_request_subscription_type.py
  cooperator/models/account_invoice.py
  cooperator/models/partner.py
  cooperator/models/product.py
  cooperator/models/subscription_register.py
  cooperator/models/subscription_request.py
  cooperator/readme/DESCRIPTION.rst
  cooperator/readme/HISTORY.rst
  cooperator/readme/INSTALL.rst
  cooperator/report/account_invoice_report.py
  cooperator/report/cooperator_certificat_G001.xml
  cooperator/report/cooperator_invoice_G002.xml
  cooperator/report/reports.xml
  cooperator/security/res_groups.xml
  cooperator/tests/test_base.py
  cooperator/tests/test_cooperator.py
  cooperator/views/account_invoice_view.xml
  cooperator/views/res_partner_view.xml
  cooperator/wizard/create_subscription_from_partner.py
  cooperator/wizard/create_subscription_from_partner.xml
Labels: needs review, bot is merging ⏳

#362 [12.0][REF] include representative address type in cooperator
  cooperator/__manifest__.py
  cooperator/models/partner.py
  cooperator/readme/ROADMAP.rst
Labels: needs review, bot is merging ⏳

#363 [14.0][REF] include representative address type in cooperator
  cooperator/__manifest__.py
  cooperator/models/partner.py
  cooperator/readme/ROADMAP.rst
Labels: ready to merge, needs review, bot is merging ⏳, approved

#374 [12.0][IMP] portal_recaptcha: backport changes from migration to 14.0
  portal_recaptcha/i18n/website_recaptcha_reloaded.pot
  portal_recaptcha/models/portal_mixin.py
  portal_recaptcha/views/res_config.xml
Labels: needs review

#392 [14.0][IMP] add deprecation warning to `subscription.request.create_comp_sub_req()`
  cooperator/models/subscription_request.py
Labels: needs review, bot is merging ⏳

#375 [12.0][IMP] cooperator_website: backport changes from migration to 14.0
  .pre-commit-config.yaml
  cooperator/static/src/js/jquery.inputmask.bundle.js
  cooperator_website/__manifest__.py
  cooperator_website/controllers/main.py
  cooperator_website/data/website_cooperator_data.xml
  cooperator_website/i18n/cooperator_website.pot
  cooperator_website/i18n/fr.po
  cooperator_website/i18n/fr_BE.po
  cooperator_website/static/src/js/cooperator.js
  cooperator_website/views/subscription_template.xml
  easy_my_coop_loan_website/static/src/js/loan_issue.js
Labels: needs review, bot is merging ⏳
