Repository coopiteasy/vertical-cooperative, pull requests merged in 2022-06, with the labels that each got.

#304 [ADD] cooperator_website_uppercase_lastname
  cooperator_website_uppercase_lastname/README.rst
  cooperator_website_uppercase_lastname/__init__.py
  cooperator_website_uppercase_lastname/__manifest__.py
  cooperator_website_uppercase_lastname/controllers/__init__.py
  cooperator_website_uppercase_lastname/controllers/main.py
  cooperator_website_uppercase_lastname/readme/CONTRIBUTORS.rst
  cooperator_website_uppercase_lastname/readme/DESCRIPTION.rst
  cooperator_website_uppercase_lastname/static/description/index.html
  setup/cooperator_website_uppercase_lastname/odoo/addons/cooperator_website_uppercase_lastname
  setup/cooperator_website_uppercase_lastname/setup.py
Labels: bot is merging ⏳

#330 [FIX] easy_my_coop: Fix name computation crash
  easy_my_coop/models/subscription_request.py
  easy_my_coop/readme/newsfragments/330.bugfix.rst
Labels: needs review, bot is merging ⏳, approved

#333 12.0 fix partner age migration
  partner_age/__init__.py
  partner_age/__manifest__.py
  rename_deprecated_modules.py
  setup/partner_age/odoo/addons/partner_age
  setup/partner_age/setup.py
  uninstall_deprecated_modules.py
Labels: needs review, bot is merging ⏳
